[package]
name = "simple-saca"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.2", features = ["derive"] }
needletail = "0.5.1"
rayon = "1.7.0"
libc = "0.2.147"
libdivsufsort-rs = "0.1.2"
thread_local = "1.1.7"
